import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";
import "../assets/css/responsive.css";
import "../assets/css/style.scss";
import Header from "@/componentes/common/Header";
import Footer from "@/componentes/common/Footer";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from "@/componentes/provider/BootstrapClient";

export const metadata = {
  title: "Makeup by leena",
  description:
    "Makeup by Leena - Premium Makeup Artist in London for Weddings and Events.Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Bootstrap CSS CDN */}
        {/* <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        /> */}
      </head>
      <body>
        <BootstrapClient/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
